sudo: required
services:
  - docker

before_install:
  - docker build -t carolsilva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carolsilva/docker-react npm run test

language: generic